[2025-03-31 23:21:31,009: INFO: main: Welcome to our custom log]
[2025-04-01 22:56:56,892: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-01 22:56:56,920: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-01 22:56:56,938: INFO: common: created directory at: artifacts]
[2025-04-01 22:56:56,955: INFO: common: created directory at: data_ingestion]
[2025-04-01 22:56:56,976: INFO: 1120952329: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-01 22:59:00,037: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-01 22:59:00,041: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-01 22:59:00,043: INFO: common: created directory at: artifacts]
[2025-04-01 22:59:00,044: INFO: common: created directory at: data_ingestion]
[2025-04-01 22:59:00,048: INFO: 1120952329: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-01 23:02:14,805: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-01 23:02:14,810: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-01 23:02:14,812: INFO: common: created directory at: artifacts]
[2025-04-01 23:02:14,817: INFO: common: created directory at: data_ingestion]
[2025-04-01 23:02:14,825: INFO: 1120952329: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-01 23:09:28,819: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-01 23:09:28,824: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-01 23:09:28,827: INFO: common: created directory at: artifacts]
[2025-04-01 23:09:28,830: INFO: common: created directory at: data_ingestion]
[2025-04-01 23:09:28,834: INFO: 1626317731: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-01 23:44:26,140: INFO: 1626317731: File downloaded successfully: artifacts/data_ingestion/data.zip]
[2025-04-01 23:44:27,956: INFO: 1626317731: File extracted successfully to artifacts/data_ingestion]
[2025-04-02 08:18:48,788: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-02 08:18:48,791: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-02 08:18:48,793: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-02 08:18:48,795: INFO: common: created directory at: artifacts]
[2025-04-02 08:18:48,797: INFO: common: created directory at: data_ingestion]
[2025-04-02 08:18:48,798: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-02 08:37:00,610: INFO: data_ingestion: File downloaded successfully: artifacts/data_ingestion/data.zip]
[2025-04-02 08:37:02,620: INFO: data_ingestion: File extracted successfully to artifacts/data_ingestion]
[2025-04-02 08:37:02,621: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-11 19:53:46,307: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 19:53:46,321: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 19:54:01,324: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 19:54:01,326: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 19:54:18,547: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 19:54:18,549: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 19:55:23,297: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 19:55:23,303: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 21:00:03,330: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-11 21:00:03,331: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 21:00:03,347: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 21:00:03,349: INFO: common: created directory at: artifacts]
[2025-04-11 21:00:03,349: INFO: common: created directory at: data_ingestion]
[2025-04-11 21:00:03,350: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-11 21:17:50,718: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-11 21:17:50,719: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 21:17:50,720: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 21:17:50,721: INFO: common: created directory at: artifacts]
[2025-04-11 21:17:50,721: INFO: common: created directory at: data_ingestion]
[2025-04-11 21:17:50,721: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-11 21:17:50,727: ERROR: data_ingestion: Error downloading file: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=1e3q72lfBRd5KX8KulVX39q34vW3y2M2b (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000018CFFC5CFB0>: Failed to resolve 'drive.google.com' ([Errno 11001] getaddrinfo failed)"))]
[2025-04-11 21:17:50,729: ERROR: data_ingestion: Error extracting file: Zip file not found: artifacts/data_ingestion/data.zip]
[2025-04-11 21:17:50,729: ERROR: main: Zip file not found: artifacts/data_ingestion/data.zip]
Traceback (most recent call last):
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_disease_classification\main.py", line 8, in <module>
    data_ingestion.main()
  File "c:\users\prarthana\desktop\projects\kidney\kidney_disease_classification\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 15, in main
    data_ingestion.extract_zip_file()
  File "c:\users\prarthana\desktop\projects\kidney\kidney_disease_classification\src\cnnClassifier\components\data_ingestion.py", line 49, in extract_zip_file
    raise e
  File "c:\users\prarthana\desktop\projects\kidney\kidney_disease_classification\src\cnnClassifier\components\data_ingestion.py", line 40, in extract_zip_file
    raise FileNotFoundError(f"Zip file not found: {self.config.local_data_file}")
FileNotFoundError: Zip file not found: artifacts/data_ingestion/data.zip
[2025-04-11 21:18:32,089: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-11 21:18:32,091: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 21:18:32,092: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 21:18:32,093: INFO: common: created directory at: artifacts]
[2025-04-11 21:18:32,093: INFO: common: created directory at: data_ingestion]
[2025-04-11 21:18:32,093: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-11 21:20:47,390: INFO: data_ingestion: File downloaded successfully: artifacts/data_ingestion/data.zip]
[2025-04-11 21:20:48,184: INFO: data_ingestion: File extracted successfully to artifacts/data_ingestion]
[2025-04-11 21:20:48,184: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-11 21:20:52,516: INFO: main: *******************]
[2025-04-11 21:20:52,516: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-04-11 21:20:52,517: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 21:20:52,518: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 21:20:52,519: INFO: common: created directory at: artifacts]
[2025-04-11 21:20:52,520: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-04-11 21:20:52,520: ERROR: main: "'ConfigBox' object has no attribute 'include_top'"]
Traceback (most recent call last):
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\box\box.py", line 503, in __getitem__
    return super().__getitem__(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'INCLUDE_TOP'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\box\box.py", line 536, in __getattr__
    value = self.__getitem__(item, _ignore_default=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\box\box.py", line 524, in __getitem__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'INCLUDE_TOP'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\box\box.py", line 538, in __getattr__
    value = object.__getattribute__(self, item)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigBox' object has no attribute 'INCLUDE_TOP'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\box\config_box.py", line 28, in __getattr__
    return super().__getattr__(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\box\box.py", line 552, in __getattr__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'INCLUDE_TOP'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\box\box.py", line 503, in __getitem__
    return super().__getitem__(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'include_top'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\box\box.py", line 536, in __getattr__
    value = self.__getitem__(item, _ignore_default=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\box\box.py", line 524, in __getitem__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'include_top'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\box\box.py", line 538, in __getattr__
    value = object.__getattribute__(self, item)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigBox' object has no attribute 'include_top'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_disease_classification\main.py", line 21, in <module>
    obj.main()
  File "c:\users\prarthana\desktop\projects\kidney\kidney_disease_classification\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 15, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\prarthana\desktop\projects\kidney\kidney_disease_classification\src\cnnClassifier\config\configuration.py", line 50, in get_prepare_base_model_config
    params_include_top=self.params.INCLUDE_TOP,
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\box\config_box.py", line 30, in __getattr__
    return super().__getattr__(item.lower())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\box\box.py", line 552, in __getattr__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'include_top'"
[2025-04-11 21:24:36,496: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-11 21:24:36,497: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 21:24:36,514: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 21:24:36,515: INFO: common: created directory at: artifacts]
[2025-04-11 21:24:36,515: INFO: common: created directory at: data_ingestion]
[2025-04-11 21:24:36,516: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-11 21:25:45,888: INFO: data_ingestion: File downloaded successfully: artifacts/data_ingestion/data.zip]
[2025-04-11 21:25:46,498: INFO: data_ingestion: File extracted successfully to artifacts/data_ingestion]
[2025-04-11 21:25:46,499: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-11 21:25:50,032: INFO: main: *******************]
[2025-04-11 21:25:50,033: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-04-11 21:25:50,034: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 21:25:50,036: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 21:25:50,036: INFO: common: created directory at: artifacts]
[2025-04-11 21:25:50,037: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-04-11 21:26:52,197: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-11 21:26:52,313: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-11 21:26:52,393: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-04-11 22:01:00,890: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 22:01:00,893: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 22:01:00,895: INFO: common: created directory at: artifacts]
[2025-04-11 22:01:00,897: INFO: common: created directory at: artifacts\training]
[2025-04-11 22:01:01,377: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-11 22:01:38,441: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 22:01:38,445: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 22:01:38,446: INFO: common: created directory at: artifacts]
[2025-04-11 22:01:38,448: INFO: common: created directory at: artifacts\training]
[2025-04-11 22:01:38,619: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-11 22:02:23,273: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 22:02:23,276: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 22:02:23,279: INFO: common: created directory at: artifacts]
[2025-04-11 22:02:23,282: INFO: common: created directory at: artifacts\training]
[2025-04-11 22:02:23,445: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-11 22:02:33,915: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 22:02:33,918: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 22:02:33,920: INFO: common: created directory at: artifacts]
[2025-04-11 22:02:33,921: INFO: common: created directory at: artifacts\training]
[2025-04-11 22:02:34,077: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-11 22:24:15,294: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-11 22:24:15,295: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 22:24:15,339: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 22:24:15,342: INFO: common: created directory at: artifacts]
[2025-04-11 22:24:15,343: INFO: common: created directory at: data_ingestion]
[2025-04-11 22:24:15,345: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-11 22:26:25,913: INFO: data_ingestion: File downloaded successfully: artifacts/data_ingestion/data.zip]
[2025-04-11 22:26:26,558: INFO: data_ingestion: File extracted successfully to artifacts/data_ingestion]
[2025-04-11 22:26:26,559: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-11 22:26:26,559: INFO: main: *******************]
[2025-04-11 22:26:26,559: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-04-11 22:26:26,560: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 22:26:26,561: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 22:26:26,562: INFO: common: created directory at: artifacts]
[2025-04-11 22:26:26,563: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-04-11 22:26:26,879: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-11 22:26:26,984: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-11 22:26:27,083: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-04-11 22:26:27,084: INFO: main: *******************]
[2025-04-11 22:26:27,084: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-04-11 22:26:27,085: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 22:26:27,087: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 22:26:27,088: INFO: common: created directory at: artifacts]
[2025-04-11 22:26:27,089: INFO: common: created directory at: artifacts\training]
[2025-04-11 22:26:27,254: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-11 22:26:27,258: ERROR: main: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney-ct-scan-image']
Traceback (most recent call last):
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_disease_classification\main.py", line 32, in <module>
    model_trainer.main()
  File "c:\users\prarthana\desktop\projects\kidney\kidney_disease_classification\src\cnnClassifier\pipeline\stage_03_model_training.py", line 20, in main
    training.train_valid_generator()
  File "c:\users\prarthana\desktop\projects\kidney\kidney_disease_classification\src\cnnClassifier\components\model_training.py", line 25, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\keras\src\legacy\preprocessing\image.py", line 1138, in flow_from_directory
    return DirectoryIterator(
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_env\Lib\site-packages\keras\src\legacy\preprocessing\image.py", line 453, in __init__
    for subdir in sorted(os.listdir(directory)):
                         ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney-ct-scan-image'
[2025-04-11 22:28:30,608: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-11 22:28:30,609: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 22:28:30,610: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 22:28:30,611: INFO: common: created directory at: artifacts]
[2025-04-11 22:28:30,611: INFO: common: created directory at: data_ingestion]
[2025-04-11 22:28:30,611: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-11 22:29:43,420: INFO: data_ingestion: File downloaded successfully: artifacts/data_ingestion/data.zip]
[2025-04-11 22:29:43,964: INFO: data_ingestion: File extracted successfully to artifacts/data_ingestion]
[2025-04-11 22:29:43,964: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-11 22:29:43,964: INFO: main: *******************]
[2025-04-11 22:29:43,964: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-04-11 22:29:43,965: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 22:29:43,967: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 22:29:43,967: INFO: common: created directory at: artifacts]
[2025-04-11 22:29:43,967: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-04-11 22:29:44,224: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-11 22:29:44,400: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-11 22:29:44,495: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-04-11 22:29:44,496: INFO: main: *******************]
[2025-04-11 22:29:44,496: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-04-11 22:29:44,498: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 22:29:44,499: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 22:29:44,500: INFO: common: created directory at: artifacts]
[2025-04-11 22:29:44,501: INFO: common: created directory at: artifacts\training]
[2025-04-11 22:29:44,656: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-11 22:29:44,682: ERROR: main: Training.train() missing 1 required positional argument: 'callback_list']
Traceback (most recent call last):
  File "C:\Users\Prarthana\Desktop\projects\kidney\kidney_disease_classification\main.py", line 32, in <module>
    model_trainer.main()
  File "c:\users\prarthana\desktop\projects\kidney\kidney_disease_classification\src\cnnClassifier\pipeline\stage_03_model_training.py", line 21, in main
    training.train()
TypeError: Training.train() missing 1 required positional argument: 'callback_list'
[2025-04-11 22:34:04,028: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 22:34:04,032: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 22:34:04,036: INFO: common: created directory at: artifacts]
[2025-04-11 22:34:04,039: INFO: common: created directory at: artifacts\training]
[2025-04-11 22:34:04,265: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-11 22:36:41,921: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 22:36:41,926: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 22:36:41,929: INFO: common: created directory at: artifacts]
[2025-04-11 22:36:41,931: INFO: common: created directory at: artifacts\training]
[2025-04-11 22:36:42,091: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-11 22:36:59,774: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 22:36:59,777: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 22:36:59,779: INFO: common: created directory at: artifacts]
[2025-04-11 22:36:59,781: INFO: common: created directory at: artifacts\training]
[2025-04-11 22:36:59,964: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-11 22:37:19,717: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 22:37:19,721: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 22:37:19,723: INFO: common: created directory at: artifacts]
[2025-04-11 22:37:19,724: INFO: common: created directory at: artifacts\training]
[2025-04-11 22:37:19,893: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-11 22:38:01,399: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 22:38:01,404: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 22:38:01,406: INFO: common: created directory at: artifacts]
[2025-04-11 22:38:01,409: INFO: common: created directory at: artifacts\training]
[2025-04-11 22:38:01,558: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-11 22:38:11,673: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 22:38:11,676: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 22:38:11,678: INFO: common: created directory at: artifacts]
[2025-04-11 22:38:11,679: INFO: common: created directory at: artifacts\training]
[2025-04-11 22:38:11,856: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-11 22:39:57,725: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-11 22:39:57,727: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 22:39:57,728: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 22:39:57,728: INFO: common: created directory at: artifacts]
[2025-04-11 22:39:57,728: INFO: common: created directory at: data_ingestion]
[2025-04-11 22:39:57,729: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1e3q72lfBRd5KX8KulVX39q34vW3y2M2b/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-11 22:41:05,454: INFO: data_ingestion: File downloaded successfully: artifacts/data_ingestion/data.zip]
[2025-04-11 22:41:06,089: INFO: data_ingestion: File extracted successfully to artifacts/data_ingestion]
[2025-04-11 22:41:06,089: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-11 22:41:06,089: INFO: main: *******************]
[2025-04-11 22:41:06,089: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-04-11 22:41:06,090: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 22:41:06,091: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 22:41:06,092: INFO: common: created directory at: artifacts]
[2025-04-11 22:41:06,092: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-04-11 22:41:06,482: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-11 22:41:06,639: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-04-11 22:41:06,742: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-04-11 22:41:06,742: INFO: main: *******************]
[2025-04-11 22:41:06,742: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-04-11 22:41:06,743: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 22:41:06,744: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 22:41:06,745: INFO: common: created directory at: artifacts]
[2025-04-11 22:41:06,746: INFO: common: created directory at: artifacts\training]
[2025-04-11 22:41:06,895: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-11 22:41:06,920: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
